import { NextApiRequest } from 'next';

export const mailOptions = (
  email: any,
  emailToken: any,
  name: String,
  req: NextApiRequest
) => {
  const mailOptions = {
    from: 'Verify your email address <callmevaksa@gmail.com>',
    to: email.toString(),
    subject: 'Real Estate App - Verify your email address',
    html: ` <!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Open+Sans" 
    rel="stylesheet" type="text/css"><!--<![endif]--><style>
    *{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none} @media (max-width:620px){.social_block.desktop_hide .social-table{display:inline-block!important}.image_block img.big,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
    </style></head><body style="background-color:#f6f6f6;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
    style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" 
    src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/OKNOT10/email_headerfooter-01.jpg" style="display:block;height:auto;border:0;width:600px;max-width:100%" width="600" alt="enginemailer" title="enginemailer"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" 
    cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;border-right:1px solid #f0f0f0;padding-bottom:30px;padding-left:15px;padding-right:15px;padding-top:15px;vertical-align:top;border-top:0;border-bottom:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
    style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px;width:100%"><div class="alignment" align="left" style="line-height:10px"><img src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/Logos/yourlogohere_black.png_thumb.png" style="display:block;height:auto;border:0;width:200px;max-width:100%" width="200" alt="enginemailer" title="enginemailer">
    </div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#31cccc;line-height:1.5"><p style="margin:0;font-size:12px;mso-line-height-alt:72px">
    <span style="font-size:48px;"><span style="font-size:48px;">Verify your email</span></span></p></div></div></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#31cccc;line-height:1.5"><p 
    style="margin:0;font-size:12px;mso-line-height-alt:33px"><span style="font-size:22px;"><span style>Welcome ${name},</span></span></p></div></div></td></tr></table><table class="text_block block-4" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
    style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#595959;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="font-size:18px;">To be able to login to your account, you need to verify your email address by clicking the button below:&nbsp;</span></p></div></div></td></tr></table><table class="button_block block-5" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" 
    style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="left">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="#" style="height:60px;width:296px;v-text-anchor:middle;" arcsize="0%" stroke="false" fillcolor="#31cccc"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:20px"><![endif]-->
    <a href="http://${req.headers.host}/user/verify-email/${emailToken}" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#31cccc;border-radius:0px;width:auto;border-top:0px solid transparent;font-weight:undefined;border-right:0px solid transparent;border-bottom:0px solid transparent;border-left:0px solid transparent;padding-top:10px;padding-bottom:10px;font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:20px;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:30px;padding-right:30px;font-size:20px;display:inline-block;letter-spacing:normal;"><span dir="ltr" style="word-break:break-word;"><span style="line-height: 40px;" dir="ltr" data-mce-style>Verify your email address</span></span></span></a>
    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="text_block block-6" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#595959;line-height:1.5"><p 
    style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="font-size:18px;">If you didn't register your account or requested to verify your email address, you don't have to do anything.</span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table 
    class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;border-right:1px solid #f0f0f0;vertical-align:top;border-top:0;border-bottom:0"><table class="image_block block-1" width="100%" 
    border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/OKNOT10/email_headerfooter-01.jpg" 
    style="display:block;height:auto;border:0;width:598px;max-width:100%" width="598" alt="enginemailer" title="enginemailer"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" 
    role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6;color:#333;width:600px" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0"><table class="social_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
    role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:center;padding-right:0;padding-left:0"><div class="alignment" align="center"><table class="social-table" width="185px" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block"><tr><td style="padding:0 5px 0 0"><a href="https://www.facebook.com/" target="_blank"><img 
    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/facebook@2x.png" width="32" height="32" alt="Facebook" title="Facebook" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://twitter.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/twitter@2x.png" width="32" height="32" alt="Twitter" 
    title="Twitter" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://plus.google.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/googleplus@2x.png" width="32" height="32" alt="Google+" title="Google+" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0">
    <a href="https://www.linkedin.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/linkedin@2x.png" width="32" height="32" alt="LinkedIn" title="LinkedIn" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://instagram.com/" target="_blank"><img 
    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/instagram@2x.png" width="32" height="32" alt="Instagram" title="Instagram" style="display:block;height:auto;border:0"></a></td></tr></table></div></td></tr></table></td><td class="column column-2" width="50%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-right:1px solid #f0f0f0;padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
    style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:14.399999999999999px;color:#414141;line-height:1.2"><p style="margin:0;font-size:11px;text-align:center;mso-line-height-alt:13.2px">
    <span style="font-size:11px;"><span style="font-size:11px;"><a style="text-decoration: none; color: #414141;" href="#" target="_blank" rel="noopener noreferrer">callmevaksa@gmail.com</a> | <a style="text-decoration: none; color: #414141;" href="#" target="_blank" rel="noopener noreferrer">+387 000 000 000</a></span></span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr>
    </tbody></table></td></tr></tbody></table><!-- End --><div style="background-color:transparent;">
        <div style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="block-grid ">
            <div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;">
                <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="background-color:transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width: 500px;"><tr class="layout-full-width" style="background-color:transparent;"><![endif]-->
                <!--[if (mso)|(IE)]><td align="center" width="500" style=" width:500px; padding-right: 0px; padding-left: 0px; padding-top:15px; padding-bottom:15px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
                <div class="col num12" style="min-width: 320px;max-width: 500px;display: table-cell;vertical-align: top;">
                    <div style="background-color: transparent; width: 100% !important;">
                        <!--[if (!mso)&(!IE)]><!--><div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:15px; padding-bottom:15px; padding-right: 0px; padding-left: 0px;">
                            <!--<![endif]-->
                            <!--[if (!mso)&(!IE)]><!-->
                        </div><!--<![endif]-->
                    </div>
                </div>
                <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->
            </div>
        </div>
    </div></body></html>`,
  };

  return mailOptions;
};

export const resetOptions = (
  email: any,
  id: any,
  passwordToken: any,
  name: String,
  req: NextApiRequest
) => {
  const mailOptions = {
    from: 'Reset Password <callmevaksa@gmail.com>',
    to: email.toString(),
    subject: 'Real Estate App - Reset your password',
    html: ` <!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Open+Sans" 
    rel="stylesheet" type="text/css"><!--<![endif]--><style>
    *{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none} @media (max-width:620px){.social_block.desktop_hide .social-table{display:inline-block!important}.image_block img.big,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
    </style></head><body style="background-color:#f6f6f6;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
    style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" 
    src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/OKNOT10/email_headerfooter-01.jpg" style="display:block;height:auto;border:0;width:600px;max-width:100%" width="600" alt="enginemailer" title="enginemailer"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" 
    cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;border-right:1px solid #f0f0f0;padding-bottom:30px;padding-left:15px;padding-right:15px;padding-top:15px;vertical-align:top;border-top:0;border-bottom:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
    style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px;width:100%"><div class="alignment" align="left" style="line-height:10px"><img src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/Logos/yourlogohere_black.png_thumb.png" style="display:block;height:auto;border:0;width:200px;max-width:100%" width="200" alt="enginemailer" title="enginemailer">
    </div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#31cccc;line-height:1.5"><p style="margin:0;font-size:12px;mso-line-height-alt:72px">
    <span style="font-size:48px;"><span style="font-size:48px;">Verify your email</span></span></p></div></div></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#31cccc;line-height:1.5"><p 
    style="margin:0;font-size:12px;mso-line-height-alt:33px"><span style="font-size:22px;"><span style>Hello ${name},</span></span></p></div></div></td></tr></table><table class="text_block block-4" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
    style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#595959;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="font-size:18px;">To reset your password click the button below:&nbsp;</span></p></div></div></td></tr></table><table class="button_block block-5" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" 
    style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="left">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="#" style="height:60px;width:296px;v-text-anchor:middle;" arcsize="0%" stroke="false" fillcolor="#31cccc"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:20px"><![endif]-->
    <a href="http://${req.headers.host}/user/${id}/reset-password/${passwordToken}" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#31cccc;border-radius:0px;width:auto;border-top:0px solid transparent;font-weight:undefined;border-right:0px solid transparent;border-bottom:0px solid transparent;border-left:0px solid transparent;padding-top:10px;padding-bottom:10px;font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:20px;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:30px;padding-right:30px;font-size:20px;display:inline-block;letter-spacing:normal;"><span dir="ltr" style="word-break:break-word;"><span style="line-height: 40px;" dir="ltr" data-mce-style>Reset your password</span></span></span></a>
    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="text_block block-6" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:18px;color:#595959;line-height:1.5"><p 
    style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="font-size:18px;">This password link will expire after 20 minutes and will no longer work. If you didn't request to reset your password, you don't have to do anything.</span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table 
    class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;border-right:1px solid #f0f0f0;vertical-align:top;border-top:0;border-bottom:0"><table class="image_block block-1" width="100%" 
    border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/0db9f180-d222-4b2b-9371-cf9393bf4764/0bd8b69e-4024-4f26-9010-6e2a146401fb/Email%20Templates%20Assets%20Folder/OKNOT10/email_headerfooter-01.jpg" 
    style="display:block;height:auto;border:0;width:598px;max-width:100%" width="598" alt="enginemailer" title="enginemailer"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" 
    role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f6f6f6;color:#333;width:600px" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:1px solid #f0f0f0;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0"><table class="social_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
    role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:center;padding-right:0;padding-left:0"><div class="alignment" align="center"><table class="social-table" width="185px" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block"><tr><td style="padding:0 5px 0 0"><a href="https://www.facebook.com/" target="_blank"><img 
    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/facebook@2x.png" width="32" height="32" alt="Facebook" title="Facebook" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://twitter.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/twitter@2x.png" width="32" height="32" alt="Twitter" 
    title="Twitter" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://plus.google.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/googleplus@2x.png" width="32" height="32" alt="Google+" title="Google+" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0">
    <a href="https://www.linkedin.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/linkedin@2x.png" width="32" height="32" alt="LinkedIn" title="LinkedIn" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://instagram.com/" target="_blank"><img 
    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-dark-gray/instagram@2x.png" width="32" height="32" alt="Instagram" title="Instagram" style="display:block;height:auto;border:0"></a></td></tr></table></div></td></tr></table></td><td class="column column-2" width="50%" 
    style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-right:1px solid #f0f0f0;padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
    style="font-size:12px;font-family:Open Sans,Helvetica,Arial,sans-serif;mso-line-height-alt:14.399999999999999px;color:#414141;line-height:1.2"><p style="margin:0;font-size:11px;text-align:center;mso-line-height-alt:13.2px">
    <span style="font-size:11px;"><span style="font-size:11px;"><a style="text-decoration: none; color: #414141;" href="#" target="_blank" rel="noopener noreferrer">callmevaksa@gmail.com</a> | <a style="text-decoration: none; color: #414141;" href="#" target="_blank" rel="noopener noreferrer">+387 000 000 000</a></span></span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr>
    </tbody></table></td></tr></tbody></table><!-- End --><div style="background-color:transparent;">
        <div style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="block-grid ">
            <div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;">
                <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="background-color:transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width: 500px;"><tr class="layout-full-width" style="background-color:transparent;"><![endif]-->
                <!--[if (mso)|(IE)]><td align="center" width="500" style=" width:500px; padding-right: 0px; padding-left: 0px; padding-top:15px; padding-bottom:15px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
                <div class="col num12" style="min-width: 320px;max-width: 500px;display: table-cell;vertical-align: top;">
                    <div style="background-color: transparent; width: 100% !important;">
                        <!--[if (!mso)&(!IE)]><!--><div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:15px; padding-bottom:15px; padding-right: 0px; padding-left: 0px;">
                            <!--<![endif]-->
                            <!--[if (!mso)&(!IE)]><!-->
                        </div><!--<![endif]-->
                    </div>
                </div>
                <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->
            </div>
        </div>
    </div></body></html>`,
  };

  return mailOptions;
};

export default { mailOptions, resetOptions };
